name: Release

# on:
#   push:
#     tags:
#     - 'v*'
on:
  push:


env:
  AWS_REGION: "eu-central-1"
  AWS_ROLE: arn:aws:iam::519140963702:role/TestGithubActionsRole
  AWS_S3_PATH: s3://tarabarova-test-ga
  CARGO_TERM_COLOR: always

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup rust

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown.

      - name: Install wasm bindgen
        run: cargo install wasm-bindgen-cli

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
      - run: wasm-bindgen --out-name ppoid --out-dir out --target web ./target/wasm32-unknown-unknown/release/ppoid.wasm
      - run: cp -a ./static/. ./out/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: out



  # release:
  #   runs-on: ubuntu-latest
  #   needs: build-deploy-prod

  #   steps:
  #   - name: Download a Build Artifact
  #     uses: actions/download-artifact@v3.0.0
  #     with:
  #       name: build
  #       path: build

  #   - name: Archive artifacts
  #     run: zip -r build.zip build

  #   - name: Get release
  #     id: get_release
  #     uses: bruceadams/get-release@v1.2.3
  #     env:
  #       GITHUB_TOKEN: ${{ github.token }}

  #   - uses: actions/upload-release-asset@v1.0.1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       upload_url: ${{ steps.get_release.outputs.upload_url }}
  #       asset_path: build.zip
  #       asset_name: build.zip
  #       asset_content_type: application/zip