name: Release

on:
  push:
    tags:
    - 'v*'

env:
  AWS_REGION: "eu-central-1"
  AWS_ROLE: arn:aws:iam::519140963702:role/TestGithubActionsRole
  AWS_S3_PATH: s3://tarabarova-test-ga
  CARGO_TERM_COLOR: always
  DISTRIBUTION: ETM68UEEIWG3H

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm bindgen
        run: cargo install wasm-bindgen-cli

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
      - run: wasm-bindgen --out-name ppoid --out-dir out --target web ./target/wasm32-unknown-unknown/release/ppoid.wasm
      - run: cp -a ./static/. ./out/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync out ${{ env.AWS_S3_PATH }} --delete

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.DISTRIBUTION }}
          PATHS: "/*"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: out


  release:
    runs-on: ubuntu-latest
    needs: build-deploy

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: build
        path: build

    - name: Archive artifacts
      run: zip -r build.zip build

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: build.zip
        asset_name: build.zip
        asset_content_type: application/zip